/*
 * Copyright (C) 2013 by SUTD (Singapore)
 * All rights reserved.
 *
 * 	Author: SUTD
 *  Version:  $Revision: 1 $
 */

package tzuyu.core.main;

import icsetlv.variable.VariableNameCollector.VarNameCollectionMode;

import org.junit.Before;
import org.junit.Test;

import sav.commons.testdata.opensource.TestPackage;

/**
 * @author LLT
 *
 */
public class FaultLocatePackageTest extends AbstractTzPackageTest {
	private TzuyuCore tzCore;
	private FaultLocateParams params;
	
	@Before
	public void setup() {
		super.setup();
		tzCore = new TzuyuCore(context, appData);
		params = new FaultLocateParams();
		params.setMachineLearningEnable(true);
		params.setRankToExamine(3);
		params.setRunMutation(false);
		params.setUseSlicer(true);
		params.setValueRetrieveLevel(3);
		params.setVarNameCollectionMode(VarNameCollectionMode.FULL_NAME);
	}
	
	public void runFaultLocate(TestPackage testPkg) throws Exception {
		prepare(testPkg);
		params.setTestingClassNames(testingClassNames);
		params.setTestingPkgs(testingPackages);
		params.setJunitClassNames(junitClassNames);
		tzCore.faultLocate(params);
	}
	
	/**
	 * test part
	 */
	
	/**
	 * ASTParserTokenManager: 2220
	 * & ASTParserTokenManager: 69
	 */
	@Test
	public void testjavaparser46() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("javaparser", "46");
		params.setRankToExamine(3);
		params.setVarNameCollectionMode(VarNameCollectionMode.HIGHEST_LEVEL_VAR);
		runFaultLocate(testPkg);
	}
	
	/**
	 * 
	 */
	@Test
	public void testjavaparser57() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("javaparser", "57");
		params.setRankToExamine(3);
		params.setRunMutation(false);
		params.setMachineLearningEnable(true);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testjavaparser69() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("javaparser", "69");
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testjodatime90() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("joda-time", "90");
		params.setRankToExamine(3);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testjodatime194() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("joda-time", "194");
		params.setRankToExamine(7);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testjodatime233() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("joda-time", "233");
		params.setRankToExamine(3);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testjodatime227() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("joda-time", "227");
		params.setRankToExamine(6);
		params.setValueRetrieveLevel(2);
		params.setUseSlicer(false);
		params.setRunMutation(true);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testDiffUtils8() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("java-diff-utils", "8");
		params.setRankToExamine(3);
		params.setRunMutation(false);
		params.setValueRetrieveLevel(2);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testDiffUtils10() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("java-diff-utils", "10");
		params.setRankToExamine(3);
		params.setValueRetrieveLevel(2);
		params.setRunMutation(true);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testDiffUtils12() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("java-diff-utils", "12");
		params.setRankToExamine(3);
		runFaultLocate(testPkg);
	}
	
	/**
	 * not really a bug, this result is acceptable because of the idea of myers algorithm
	 */
	@Test
	public void testDiffUtils18() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("java-diff-utils", "18");
		params.setRankToExamine(3);
		runFaultLocate(testPkg);
	}
	
	/**
	 * Parsing add-only parts of unified diffs generated by "diff -U 0 ..." fails
	 * llt: not sure if this is really a bug, it depends on the requirement. 
	 * */
	@Test
	public void testDiffUtils20() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("java-diff-utils", "20");
		params.setRankToExamine(3);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testCommonsMath1196() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("apache-commons-math", "1196");
		params.setRankToExamine(3);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testCommonsCli233() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("commons-cli", "233-v1.2");
		params.setRankToExamine(3);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testOpenCsv102() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("opencsv", "102");
		params.setRankToExamine(4);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testOpenCsv108() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("opencsv", "108");
		params.setRankToExamine(4);
		runFaultLocate(testPkg);
	}
	
	@Test
	public void testOpenCsv106() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("opencsv", "106");
		params.setRankToExamine(4);
		params.setVarNameCollectionMode(VarNameCollectionMode.HIGHEST_LEVEL_VAR);
		runFaultLocate(testPkg);
	}
}
