/*
 * Copyright (C) 2013 by SUTD (Singapore)
 * All rights reserved.
 *
 * 	Author: SUTD
 *  Version:  $Revision: 1 $
 */

package tzuyu.core.main;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import org.apache.commons.io.FileUtils;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import faultLocalization.LineCoverageInfo;

import sav.common.core.Constants;
import sav.commons.AbstractTest;
import sav.commons.TestConfiguration;
import sav.commons.testdata.opensource.TestPackage;
import sav.commons.testdata.opensource.TestPackage.TestDataColumn;
import tzuyu.core.inject.ApplicationData;

/**
 * @author LLT
 *
 */
public class FixturePackageLocalTest extends AbstractTest {
	private SingleSeededBugFixture fixture;
	private ApplicationData appData;
	
	@Before
	public void setup() throws FileNotFoundException {
		SystemConfiguredDataProvider context = new SystemConfiguredDataProvider();
		appData = context.getAppData();
		fixture = new SingleSeededBugFixture();
		fixture.setContext(context);
		fixture.useSlicer(true);
		fixture.javaHome("D:/_1_Projects/Tzuyu/tools/jdk1.6.0_26-64b");
		fixture.projectClassPath(TestConfiguration.getTarget("slicer.javaslicer"));
		fixture.projectClassPath(TestConfiguration.getTzAssembly(Constants.SAV_COMMONS_ASSEMBLY));
		fixture.projectClassPath(TestConfiguration.getInstance().getJavaBin());
	}
	
	public void runTest(TestPackage testPkg) throws Exception {
		List<String> expectedBugLocations = prepare(testPkg);
		if (fixture.useSlicer) {
			fixture.analyze2(testPkg.getValues(TestDataColumn.ANALYZING_PACKAGES));
		} else {
			fixture.analyze();
		}
		List<LineCoverageInfo> lineCoverageInfos = fixture.getReport().getLineCoverageInfos();
		Collections.reverse(lineCoverageInfos);
		printList(lineCoverageInfos);
		Assert.assertTrue(expectedBugLocations.isEmpty() || fixture.bugWasFound());
	}
	
	public List<String> prepare(TestPackage testPkg) throws Exception {
		//TODO LLT: refactor
		appData.setAppTarget(testPkg.getClassPaths().get(0));
		fixture.projectClassPaths(testPkg.getClassPaths());
		for (String libs : testPkg.getLibFolders()) {
			addLibs(libs);
		}
		if (!fixture.useSlicer) {
			for (String clazz : testPkg.getValues(TestDataColumn.ANALYZING_CLASSES)) {
				fixture.programClass(clazz);
			}
		}
		for (String clazz : testPkg.getValues(TestDataColumn.TEST_CLASSES)) {
			fixture.programTestClass(clazz);
		}		
		List<String> expectedBugLocations = testPkg.getValues(TestDataColumn.EXPECTED_BUG_LOCATION);
		if (!expectedBugLocations.isEmpty()) {
			fixture.expectedBugLine(expectedBugLocations.get(0));
		}
		updateSystemClasspath(appData.getAppClasspaths());
		return expectedBugLocations;
	}
	
	private void addLibs(String... libFolders) throws Exception {
		for (String libFolder : libFolders) {
			Collection<?> files = FileUtils.listFiles(new File(libFolder),
					new String[] { "jar" }, true);
			for (Object obj : files) {
				File file = (File) obj;
				fixture.projectClassPath(file.getAbsolutePath());
			}
		}
	}
	
	/**
	 * generated by {@link PkgTestGenerator}.
	 * a testcase will be generated corresponding to each package defined in /etc/testdata.csv
	 */
	//	Generated part
	
	@Test
	public void testjavaparser46() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("javaparser", "46");
		fixture.useSlicer(true);
		runTest(testPkg);
	}
	
	@Test
	public void testjavaparser57() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("javaparser", "57");
		fixture.useSlicer(true);
		runTest(testPkg);
	}
	
	@Test
	public void testjavaparser63() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("javaparser", "63");
		fixture.useSlicer(false);
		runTest(testPkg);
	}
	
	@Test
	public void testjodatime194() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("joda-time", "194");
		fixture.useSlicer(false);
		runTest(testPkg);
	}
	
	@Test
	public void testjodatime201() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("joda-time", "201");
		fixture.useSlicer(true);
		runTest(testPkg);
	}
	
	@Test
	public void testjodatime187() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("joda-time", "187");
		fixture.useSlicer(true);
		runTest(testPkg);
	}
	
	@Test
	public void testjavadiffutils18() throws Exception {
		TestPackage testPkg = TestPackage.getPackage("java-diff-utils", "18");
		fixture.useSlicer(true);
		runTest(testPkg);
	}
	//	End generated part
}
