/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 17 07:38:39 GMT 2017
 */

package org.apache.commons.math;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math.Testing;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Testing_ESTest extends Testing_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Testing testing0 = new Testing();
      testing0.multiCond(9.99743, 608.2840509079788);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Testing testing0 = new Testing();
      testing0.multiCond(8.0, 1.0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Testing testing0 = new Testing();
      testing0.multiCond(330.38187118, (-2778.532));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Testing testing0 = new Testing();
      testing0.multiCond(1.0, 1.0);
  }
}
