/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 09 12:53:09 GMT 2018
 */

package cfgcoverage.jacoco.testdata;

import org.junit.Test;

public class Testing_ESTest {
	
	@Test
	  public void test0()  throws Throwable  {
	      Testing testing0 = new Testing();
	      testing0.test(8.0, 8.0);
	  }
	@Test
	  public void test1()  throws Throwable  {
	      Testing testing0 = new Testing();
	      testing0.test(648.705363583215, 1354.57129);
	  }
	@Test
	  public void test2()  throws Throwable  {
	      Testing testing0 = new Testing();
	      testing0.test(8.178959502740419, (-796.60026488));
	  }
	@Test
	  public void test3()  throws Throwable  {
	      Testing testing0 = new Testing();
	      testing0.test((-1266.6905497684336), (-1266.6905497684336));
	  }
//  @Test(timeout = 4000)
//  public void test0()  throws Throwable  {
//      Testing testing0 = new Testing();
//      testing0.test(8.0, 0.0);
//  }
//
//  @Test(timeout = 4000)
//  public void test1()  throws Throwable  {
//      Testing testing0 = new Testing();
//      testing0.test(2821.202, 2821.202);
//  }
//
//  @Test(timeout = 4000)
//  public void test2()  throws Throwable  {
//      Testing testing0 = new Testing();
//      testing0.test(8.18470736385903, 0.0);
//  }
//
//  @Test(timeout = 4000)
//  public void test3()  throws Throwable  {
//      Testing testing0 = new Testing();
//      testing0.test((-1.0), 0.0);
//  }
}
