package tester;

import tzuyu.engine.TzClass;
import tzuyu.engine.model.Variable;

/**
 * The interface for selecting concrete of sequences that generate the concrete
 * argument for a type.
 * 
 * @author Spencer Xiao
 * 
 */
public interface IParameterSelector {

	public Variable selectVariable(Variable receiver, Class<?> type);
	/**
	 * Generate a variable for the given type. The type could be primitive or
	 * reference types.
	 * 
	 * @param type
	 * @return
	 */
	public Variable selectNewVariable(Class<?> type);

	public Variable selectExistingVariable(Variable receiver, Class<?> type);

	public Variable selectCachedVariable(Class<?> type);

	/**
	 * Generate a null value for the give type as the main object of the method
	 * calls defined in this type.
	 * 
	 * @param type
	 * @return
	 */
	public Variable selectNullReceiver(Class<?> type);

	/**
	 * Generate a variable as the main object for the method call defined in the
	 * give type. The variable is generated by calling the constructor with
	 * least number of parameters in the type. For recursive constructors, we
	 * limit the number of recursion to a depth number set by the user.
	 * 
	 * @param type
	 * @return
	 */
	public Variable selectDefaultReceiver(Class<?> type);

	public void setProject(TzClass project);
}
